version: 2

sources:
  - name: raw     
    tables:
      - name: sales     
        description: "Raw sales data from gz_raw_data dataset"
      - name: product   
        description: "Raw product data from gz_raw_data dataset"
      - name: ship      
        description: "Raw shipping data from gz_raw_data dataset"




models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
